require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

# not helpful for in progress TDD
Style/EmptyMethod:
  Description: Put empty method definitions on a single line.
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiterals:
  EnforcedStyle: double_quotes
